# reviewers를 설정할지에 대한 true or false
 addReviewers: true

 # assignees를 설정할지에 대한 true or false (author는 pr open한 user)
 addAssignees: true

 # reviewers로 지정할 대상 (GitHub user name)
 reviewers:
   - djpark0402
   - k3255

 # 지정한 숫자만큼 리뷰어가 등록
 # 0으로 설정하면 모든 리뷰어가 지정 (default: 0)
 numberOfReviewers: 2

 # A list of assignees, overrides reviewers if set
 assignees:
   - ss4076
   - k3255
# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
 numberOfAssignees: 2
